import { ref } from 'vue'

export default function useFlagTypes() {
  return ref([
    {
      id: 'abrosexual',
      label: 'Abrosexual',
      bars: ['#77CC94', '#B5E5CC', '#FCFEFF', '#E997B5', '#DC406C'],
    },
    {
      id: 'aceflux',
      label: 'Aceflux',
      bars: ['#C82067', '#BCC5C6', '#EC6D87', '#91479B', '#800080'],
    },
    {
      id: 'agender',
      label: 'Agender',
      bars: ['#000', '#BCC5C6', '#FFF', '#B5F582', '#FFF', '#BCC5C6', '#000'],
    },
    {
      id: 'ally',
      label: 'Ally',
      bars: [
        '#000',
        '#FFF',
        '#000',
        '#FFF',
        '#000',
        '#FFF',
        '#E60000',
        '#FF8E00',
        '#FFEF00',
        '#00821B',
        '#004BFF',
        '#770089',
      ],
    },
    {
      id: 'androgyne',
      label: 'Androgyne',
      bars: ['#FE007F', '#9832FF', '#00B8E7'],
    },
    {
      id: 'angled-aroace',
      label: 'Angled Aroace',
      bars: ['#FBE32C', '#F5FFAC', '#EDECCC', '#120B06'],
    },
    {
      id: 'aroaceflux',
      label: 'Aroaceflux',
      bars: ['#F8575D', '#FE7C85', '#FFCDE5', '#6B8FD5', '#3B3F94'],
    },
    {
      id: 'aroflux',
      label: 'Aroflux',
      bars: ['#D5205C', '#EB736F', '#EFE6B0', '#A9D275', '#3CA648'],
    },
    {
      id: 'aromantic',
      label: 'Aromantic',
      bars: ['#3AA740', '#A8D47A', '#FFF', '#ABABAB', '#000'],
    },
    {
      id: 'aromantic-asexual',
      label: 'Aromantic Asexual',
      bars: ['#E38D00', '#EDCE00', '#FFF', '#62B0DD', '#1A3555'],
    },
    {
      id: 'aromantic-spectrum',
      label: 'Aromantic Spectrum',
      bars: ['#3F9F52', '#97CF7C', '#F2FCCF', '#186264', '#052127'],
    },
    {
      id: 'asexual',
      label: 'Asexual',
      bars: ['#000', '#A6A7A6', '#FFF', '#820082'],
    },
    {
      id: 'autoromantic',
      label: 'Autoromantic',
      bars: ['#93D2E4', '#3EA442', '#7B7B7B'],
    },
    {
      id: 'bigender',
      label: 'Bigender',
      bars: [
        '#C67BA5',
        '#EFA9CF',
        '#D7C9EA',
        '#FFF',
        '#D7C9EA',
        '#9CC9EA',
        '#6D84D3',
      ],
    },
    {
      id: 'bigender-alt',
      label: 'Bigender (Alternative)',
      bars: ['#ED78AB', '#FEF54D', '#FFF', '#AE6DBE', '#719EE3'],
    },
    {
      id: 'bisexual',
      label: 'Bisexual',
      bars: ['#D80071', '#744E96', '#0035A9'],
    },
    {
      id: 'boyflux',
      label: 'Boyflux',
      bars: [
        '#D7E9F8',
        '#6FACF5',
        '#023670',
        '#9EEDAC',
        '#023670',
        '#6FACF5',
        '#D7E9F8',
      ],
    },
    {
      id: 'ceterosexual',
      label: 'Ceterosexual',
      bars: ['#FCF980', '#169C47', '#FFF', '#000'],
    },
    {
      id: 'cupioromantic',
      label: 'Cupioromantic',
      bars: ['#FCA9A3', '#FDC5C0', '#FFF', '#C8BFE6', '#A0A0A0'],
    },
    {
      id: 'demiboy',
      label: 'Demiboy',
      bars: [
        '#7F7F7F',
        '#C4C4C4',
        '#9AD9EB',
        '#FFF',
        '#9AD9EB',
        '#C4C4C4',
        '#7F7F7F',
      ],
    },
    {
      id: 'demiflux',
      label: 'Demiflux',
      bars: [
        '#7F7F7F',
        '#DADADA',
        '#FFB6B8',
        '#F4F691',
        '#9AD9EB',
        '#DADADA',
        '#7F7F7F',
      ],
    },
    {
      id: 'demigender',
      label: 'Demigender',
      bars: [
        '#7F7F7F',
        '#C4C4C4',
        '#FAFF72',
        '#FFF',
        '#FAFF72',
        '#C4C4C4',
        '#7F7F7F',
      ],
    },
    {
      id: 'demigirl',
      label: 'Demigirl',
      bars: [
        '#7F7F7F',
        '#C4C4C4',
        '#FFAEC9',
        '#FFF',
        '#FFAEC9',
        '#C4C4C4',
        '#7F7F7F',
      ],
    },
    {
      id: 'demigirlflux',
      label: 'Demigirlflux',
      bars: [
        '#7F7F7F',
        '#C4C4C4',
        '#A24AA3',
        '#FEAFC9',
        '#FFF',
        '#FEAFC9',
        '#A24AA3',
        '#C4C4C4',
        '#7F7F7F',
      ],
    },
    {
      id: 'demisexual',
      label: 'Demisexual',
      bars: ['#000', '#FFF', '#6f0071', '#D3D3D3'],
    },
    {
      id: 'demiromantic',
      label: 'Demiromantic',
      bars: ['#000', '#FFF', '#3AA740', '#D3D3D3'],
    },
    {
      id: 'fraysexual',
      label: 'Fraysexual',
      bars: ['#226CB5', '#93E7DD', '#FFF', '#636363'],
    },
    {
      id: 'mlm',
      label: 'MLM',
      bars: [
        '#008F72',
        '#1BD0AD',
        '#9BEAC4',
        '#FFF',
        '#7DB1E5',
        '#4E45CD',
        '#390B7A',
      ],
    },
    {
      id: 'genderfluid',
      label: 'Genderfluid',
      bars: ['#FF77A5', '#F5F5F5', '#C009D8', '#232323', '#2C39BF'],
    },
    {
      id: 'genderfae',
      label: 'Genderfae',
      bars: [
        '#95C4A4',
        '#C2DEAE',
        '#F9FACE',
        '#FFF',
        '#FCA2C5',
        '#DB8AE3',
        '#AB7EDD',
      ],
    },
    {
      id: 'genderqueer',
      label: 'Genderqueer',
      bars: ['#B880DE', '#FFF', '#478318'],
    },
    {
      id: 'girlflux',
      label: 'Girlflux',
      bars: [
        '#F8E6D8',
        '#F1526D',
        '#BF0310',
        '#E8C586',
        '#BF0310',
        '#F1526D',
        '#F8E6D8',
      ],
    },
    {
      id: 'greyromantic',
      label: 'Greyromantic',
      bars: ['#2DA038', '#AFB2Af', '#FFF', '#AFB2Af', '#2DA038'],
    },
    {
      id: 'greysexual',
      label: 'Greysexual',
      bars: ['#740195', '#AEB2AA', '#FFF', '#AEB2AA', '#740195'],
    },
    {
      id: 'intersex',
      label: 'Intersex',
      bars: ['#FFD900', '#7A00AC'],
    },
    {
      id: 'intersex-progress-pride',
      label: 'Intersex Progress Pride',
      bars: [
        '#E60000',
        '#FF8E00',
        '#FFEF00',
        '#00821B',
        '#004BFF',
        '#770089',
        '#000',
        '#794E10',
        '#5CCFFA',
        '#F4ABB8',
        '#FFF',
        '#FFD900',
        '#7A00AC',
      ],
    },
    {
      id: 'lesbian',
      label: 'Lesbian',
      bars: ['#D52800', '#FD9954', '#FFF', '#D261A4', '#A40061'],
    },
    {
      id: 'lithromantic',
      label: 'Lithromantic',
      bars: ['#F14952', '#FF9E5E', '#FFF546', '#FFF', '#2A2A2A'],
    },
    {
      id: 'nonbinary',
      label: 'NonBinary',
      bars: ['#FEF32A', '#FEFEFE', '#9D57D2', '#000'],
    },
    {
      id: 'neutrois',
      label: 'Neutrois',
      bars: ['#FFF', '#22B14C', '#000'],
    },
    {
      id: 'omnisexual',
      label: 'Omnisexual',
      bars: ['#FF9DCF', '#FF51C0', '#1A0042', '#675FFF', '#8EA9FF'],
    },
    {
      id: 'oriented-aroace',
      label: 'Oriented Aroace',
      bars: ['#060634', '#81A5B8', '#FFF', '#2FB3A4'],
    },
    {
      id: 'pangender',
      label: 'Pangender',
      bars: [
        '#FFF798',
        '#FFDDCD',
        '#FFEBFB',
        '#FFF',
        '#FFEBFB',
        '#FFDDCD',
        '#FFF798',
      ],
    },
    {
      id: 'pansexual',
      label: 'Pansexual',
      bars: ['#FF148E', '#FFDA00', '#14B5FF'],
    },
    {
      id: 'polysexual',
      label: 'Polysexual',
      bars: ['#F614BA', '#00D769', '#1593F5'],
    },
    {
      id: 'philadelphia-pride',
      label: 'Philadelphia Pride',
      bars: [
        '#000',
        '#794E10',
        '#E60000',
        '#FF8E00',
        '#FFEF00',
        '#00821B',
        '#004BFF',
        '#770089',
      ],
    },
    {
      id: 'pride',
      label: 'Pride',
      bars: ['#E60000', '#FF8E00', '#FFEF00', '#00821B', '#004BFF', '#770089'],
    },
    {
      id: 'progress-pride',
      label: 'Progress Pride',
      bars: [
        '#E60000',
        '#FF8E00',
        '#FFEF00',
        '#00821B',
        '#004BFF',
        '#770089',
        '#000',
        '#794E10',
        '#5CCFFA',
        '#F4ABB8',
        '#FFF',
      ],
    },
    {
      id: 'quoiromantic',
      label: 'Quoiromantic',
      bars: ['#000', '#FFF', '#98DC31', '#24D0E4'],
    },
    {
      id: 'recipromantic',
      label: 'Recipromantic',
      bars: ['#E84671', '#F0B2DC', '#ADF6B2', '#FFF', '#000'],
    },
    {
      id: 'transgender',
      label: 'Transgender',
      bars: ['#5CCFFA', '#F4ABB8', '#FFF', '#F4ABB8', '#5CCFFA'],
    },
    {
      id: 'trigender',
      label: 'Trigender',
      bars: ['#FF95C4', '#9580FF', '#6AD969', '#9580FF', '#FF95C4'],
    },
  ])
}
